# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_classification_job_jobapplication_userratingavail_userratingrender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
