# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20170225_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratingavail',
            name='availer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userratingrender',
            name='render',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render', to=settings.AUTH_USER_MODEL),
        ),
    ]
