# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0007_auto_20170225_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userratingrender',
            name='render',
        ),
        migrations.AddField(
            model_name='userratingavail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userratingrender',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userratingrender',
            name='renderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
