# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20170225_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratingavail',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userratingrender',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userratingrender',
            name='renderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
