# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0009_auto_20170225_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('type', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_avail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userratingavail',
            name='availer',
        ),
        migrations.RemoveField(
            model_name='userratingavail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userratingrender',
            name='renderer',
        ),
        migrations.RemoveField(
            model_name='userratingrender',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRatingAvail',
        ),
        migrations.DeleteModel(
            name='UserRatingRender',
        ),
    ]
